# Generated by Django 5.0.2 on 2024-02-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items_names',
            new_name='items',
        ),
    ]
