# Generated by Django 5.0.2 on 2024-02-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='items_names',
        ),
    ]
