# Generated by Django 5.0.2 on 2024-02-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_delete_item_rename_items_order_items_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
