# Generated by Django 5.0.2 on 2024-02-27 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_is_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_checked',
        ),
    ]
