# Generated by Django 5.0.2 on 2024-03-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_form_delete_item_delete_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_form',
            old_name='name',
            new_name='customer_name',
        ),
    ]
