# Generated by Django 5.0.2 on 2024-03-01 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_rename_name_order_form_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_form',
            old_name='customer_name',
            new_name='Name',
        ),
    ]
