# Generated by Django 5.0.2 on 2024-03-01 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_rename_customer_name_order_form_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_form',
            new_name='Order',
        ),
    ]
