# Generated by Django 5.0.2 on 2024-03-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_rename_order_form_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_of_purchase',
        ),
    ]
